version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: npm run start:dev api

    env_file:
      - ./apps/api/.env
    volumes:
      - .:/home/app
    ports:
      - '2000:1000'

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth

    env_file:
      - ./apps/api/.env
    volumes:
      - .:/home/app
    ports:
      - '2001:1000'

networks:
  default:
    external:
      name: local-docker-network