version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: npm run start:dev api

    env_file:
      - ./.env
    volumes:
      - .:/home/app
    ports:
      - '2000:1000'

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth

    env_file:
      - ./.env
    volumes:
      - .:/home/app
    ports:
      - '2001:1000'

  rabbitmq:
    image: rabbitmq

  ms-db:
    image: postgres:14.4-alpine3.16
    env_file:
      - .env
    restart: always
    volumes:
      - postdb-data:/var/lib/postgresql/data

volumes:
  postdb-data:
    driver: local

networks:
  default:
    external:
      name: local-docker-network